/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderPhone: typeof import('./src/components/HeaderPhone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/swiper.vue')['default']
    SwiperAwards: typeof import('./src/components/SwiperAwards.vue')['default']
    SwiperPhone: typeof import('./src/components/SwiperPhone.vue')['default']
    SwiperPhoneAppCase: typeof import('./src/components/SwiperPhoneAppCase.vue')['default']
    SwiperPhoneHome: typeof import('./src/components/SwiperPhoneHome.vue')['default']
    TabsPhone: typeof import('./src/components/TabsPhone.vue')['default']
    Timeline: typeof import('./src/components/timeline.vue')['default']
    TitleWrapper: typeof import('./src/components/TitleWrapper.vue')['default']
    TransWrapper: typeof import('./src/components/TransWrapper.vue')['default']
  }
}
